### ISSUE TITLE
DATABASE GAGAL TERHUBUNG

### ISSUE THREAD

**Issue by KiroFyzu** [udinesia325/MERN-COMMERCE#12]
PS D:\MERN-COMMERCE> npm start

> mern-commerce@1.0.0 start
> node app

**Server Berjalan Pada Port 8000
Menunggu Koneksi Ke Database ...
Database Gagal `Terhubung!``**

**Comment by AndyNotfound** [comment]
Sama Database Gagal terhubung terus

**Comment by udinesia325** [comment]
> PS D:\MERN-COMMERCE> npm start
> 
> > mern-commerce@1.0.0 start
> > node app
> 
> **Server Berjalan Pada Port 8000 Menunggu Koneksi Ke Database ... Database Gagal `Terhubung!``**

Sudahkah anda membuat file .env ?
Untuk isinya bisa di samakan dengan env_example
